<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>My Website</title>
<style type="text/css">
<!--
body {
	font: 100%/1.4 Verdana, Arial, Helvetica, sans-serif;
	background-color: #165D6B;
	margin: 0;
	padding: 0;
	color: #EDEDED;
}
/* ~~ Selectores de elemento/etiqueta ~~ */
ul, ol, dl { /* Debido a las diferencias existentes entre los navegadores, es recomendable no añadir relleno ni márgenes en las listas. Para lograr coherencia, puede especificar las cantidades deseadas aquí o en los elementos de lista (LI, DT, DD) que contienen. Recuerde que lo que haga aquí se aplicará en cascada en la lista .nav, a no ser que escriba un selector más específico. */
	padding: 0;
	margin: 0;
}
h1, h2, h3, h4, h5, h6, p {
	margin-top: 0;	 /* la eliminación del margen superior resuelve un problema que origina que los márgenes escapen del bloque contenedor. El margen inferior restante lo mantendrá separado de los elementos de que le sigan.  */
	padding-right: 15px;
	padding-left: 15px; /* la adición de relleno a los lados del elemento dentro de los bloques, en lugar de en los elementos del bloque propiamente dicho, elimina todas las matemáticas de modelo de cuadro. Un bloque anidado con relleno lateral también puede usarse como método alternativo. */
	text-align: justify;
	color: #FFFFFF;
	font-weight: lighter;
	font-family: Baskerville, "Palatino Linotype", Palatino, "Century Schoolbook L", "Times New Roman", serif;
}
a img { /* este selector elimina el borde azul predeterminado que se muestra en algunos navegadores alrededor de una imagen cuando está rodeada por un vínculo */
	border: none;
}
/* ~~ La aplicación de estilo a los vínculos del sitio debe permanecer en este orden (incluido el grupo de selectores que crea el efecto hover -paso por encima-). ~~ */
a:link {
	color: #42413C;
	text-decoration: underline; /* a no ser que aplique estilos a los vínculos para que tengan un aspecto muy exclusivo, es recomendable proporcionar subrayados para facilitar una identificación visual rápida */
}
a:visited {
	color: #6E6C64;
	text-decoration: underline;
}
a:hover, a:active, a:focus { /* este grupo de selectores proporcionará a un usuario que navegue mediante el teclado la misma experiencia de hover (paso por encima) que experimenta un usuario que emplea un ratón. */
	text-decoration: line-through;
	background-color: rgba(188,127,12,0.65);
	-webkit-box-shadow: 0px 0px rgba(236,18,23,1.00);
	box-shadow: 0px 0px rgba(236,18,23,1.00);
	text-shadow: 0px 0px rgba(78,193,241,0.74);
}
/* ~~ Este contenedor de anchura fija rodea a todas las demás bloques ~~ */
.container {
	width: 960px;
	background-color: #8E8485;
	margin: 0 auto; /* el valor automático de los lados, unido a la anchura, centra el diseño  */
	outline-color: #FFF;
}
/* ~~ No se asigna una anchura al encabezado. Se extenderá por toda la anchura del diseño. ~~ */
header {
	background-color: #FFFFFF;
}
/* ~~ Estas son las columnas para el diseño. ~~ 

1) El relleno sólo se sitúa en la parte superior y/o inferior de los elementos del bloque. Los elementos situados dentro de estos bloques tienen relleno a los lados. Esto le ahorra las "matemáticas de modelo de cuadro". Recuerde que si añade relleno o borde lateral al bloque propiamente dicho, éste se añadirá a la anchura que defina para crear la anchura *total*. También puede optar por eliminar el relleno del elemento en el  bloque y colocar un segundo bloque dentro de éste sin anchura y el relleno necesario para el diseño deseado.

2) No se asigna margen a las columnas, ya que todas ellas son flotantes. Si es preciso añadir un margen, evite colocarlo en el lado hacia el que se produce la flotación (por ejemplo: un margen derecho en un bloque configurado para flotar hacia la derecha). En muchas ocasiones, puede usarse relleno como alternativa. En el caso de bloques para los que deba incumplirse esta regla, deberá añadir una declaración "display:inline" a la regla del elemento del bloque para evitar un error que provoca que algunas versiones de Internet Explorer dupliquen el margen.

3) Dado que las clases se pueden usar varias veces en un documento (y que también se pueden aplicar varias clases a un elemento), se ha asignado a las columnas nombres de clases en lugar de ID. Por ejemplo, dos bloques de barra lateral podrían apilarse si fuera necesario. Si lo prefiere, éstas pueden cambiarse a ID fácilmente, siempre y cuando las utilice una sola vez por documento.

4) Si prefiere que la navegación esté a la izquierda en lugar de a la derecha, simplemente haga que estas columnas floten en dirección opuesta (todas a la izquierda en lugar de todas a la derecha) y éstas se representarán en orden inverso. No es necesario mover los bloques por el código fuente HTML.

*/
.sidebar1 {
	float: left;
	width: 180px;
	background-color: #EADCAE;
	padding-bottom: 10px;
}
.content {
	padding: 10px 0;
	width: 600px;
	float: left;
}
aside {
	float: left;
	width: 180px;
	background-color: #EADCAE;
	padding: 10px 0;
}

/* ~~ Este selector agrupado da espacio a las listas del área de .content ~~ */
.content ul, .content ol {
	padding: 0 15px 15px 40px; /* este relleno reproduce en espejo el relleno derecho de la regla de encabezados y de párrafo incluida más arriba. El relleno se ha colocado en la parte inferior para que el espacio existente entre otros elementos de la lista y a la izquierda cree la sangría. Estos pueden ajustarse como se desee. */
}

/* ~~ Los estilos de lista de navegación (pueden eliminarse si opta por usar un menú desplegable predefinido como el de Spry) ~~ */
ul.nav {
	list-style: none; /* esto elimina el marcador de lista */
	border-top: 1px solid #666; /* esto crea el borde superior de los vínculos (los demás se sitúan usando un borde inferior en el LI) */
	margin-bottom: 15px; /* esto crea el espacio entre la navegación en el contenido situado debajo */
}
ul.nav li {
	border-bottom: 1px solid #666; /* esto crea la separación de los botones  */
}
ul.nav a, ul.nav a:visited { /* al agrupar estos selectores, se asegurará de que los vínculos mantengan el aspecto de botón incluso después de haber sido visitados  */
	padding: 5px 5px 5px 15px;
	display: block; /* esto asigna propiedades de bloque al vínculo, lo que provoca que llene todo el LI que lo contiene. Esto provoca que toda el área reaccione a un clic de ratón. */
	width: 160px;  /*esta anchura hace que se pueda hacer clic en todo el botón para IE6. Puede eliminarse si no es necesario proporcionar compatibilidad con IE6. Calcule la anchura adecuada restando el relleno de este vínculo de la anchura del contenedor de barra lateral. */
	text-decoration: none;
	background-color: #B19259;
}
ul.nav a:hover, ul.nav a:active, ul.nav a:focus { /* esto cambia el color de fondo y del texto tanto para usuarios que naveguen con ratón como para los que lo hagan con teclado */
	background-color: #8E8485;
	color: #EDEDED;
}

/* ~~ El pie de página ~~ */
footer {
	padding: 10px 0;
	background-color: #FFFFFF;
	position: relative;/* esto da a IE6 el parámetro hasLayout para borrar correctamente */
	clear: both; /* esta propiedad de borrado fuerza a .container a conocer dónde terminan las columnas y a contenerlas */
}
/* ~~ Clases float/clear varias ~~ */
.fltrt {  /* esta clase puede utilizarse para que un elemento flote en la parte derecha de la página. El elemento flotante debe preceder al elemento junto al que debe aparecer en la página. */
	float: right;
	margin-left: 8px;
}
.fltlft { /* esta clase puede utilizarse para que un elemento flote en la parte izquierda de la página. El elemento flotante debe preceder al elemento junto al que debe aparecer en la página. */
	float: left;
	margin-right: 8px;
}
.clearfloat { /* esta clase puede situarse en elemento <br /> o en un bloque vacío como elemento final tras el último bloque flotante (dentro de .container) si el pie se elimina o se saca fuera de .container */
	clear:both;
	height:0;
	font-size: 1px;
	line-height: 0px;
}

/*Compatibilidad con HTML5: define nuevas etiquetas HTML5 como display:block para que los navegadores sepan cómo procesar las etiquetas correctamente. */
header, section, footer, aside, article, figure {
	display: block;
	text-align: justify;
	font-family: Verdana, Arial, Helvetica, sans-serif;
}
.container .content section section h2 span {
	font-size: 18%;
}
.container .content section h2 {
	font-family: Baskerville, "Palatino Linotype", Palatino, "Century Schoolbook L", "Times New Roman", serif;
}
-->
</style><!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]--></head>

<body>

<div class="container">
  <header>
  <a href="#"><img src="envio1/envio1/editado.jpg" width="230" height="180" alt="" /></a>

    
    <p style="font-family: Baskerville, 'Palatino Linotype', Palatino, 'Century Schoolbook L', 'Times New Roman', serif; color: #000000; text-align: right; font-size: 20px;"> Ricardo Alania Inocencio</p>	 
  
  
  </header>
  <div class="sidebar1">
    <ul class="nav">
      <div div="menu">
       		<li class="current_page_item"> <li><a href="envio1/envio1/index.html">Home</a></li>
            <li><a href=" Cursos.html">Cursos</a></li>
      		<li><a href="Proyects.html">Proyectos</a></li>
            <li><a href=" Plan Agregado de Producción.html">Plan agregado de Producción</a></li>
     		 <li><a href=" tutorial.html">Programación Líneal				</a></li>
   <li><a href= "Analisis de valor ganado.html">-Analisis de Valor Ganado			</a></li>
   
             
     		 <li><a href="envio1/envio1/Video of your interest.html">video of your interest</a></li>   
     		 
     		 
     		 </ul>
  <!-- end .sidebar1 --></div>
  <article class="content">
    <h1></h1>
    <section>
      <h2>  <center>“Analisis de Valor Ganado” </center></h2>
      
      <td> <center></center></td></td> 
      
   <center>  <iframe width="550" height="400" src="https://www.youtube.com/embed/DNd304FfYw4" frameborder="0" allowfullscreen></iframe>  </center>
     
    
     
     
     
     
     
    </section>
  <p>Definición</p> 
  
      
<p>

La Gestión del Valor Ganado es una técnica de gestión de proyectos que permite controlar la ejecución de un proyecto a través de su presupuesto y de su calendario de ejecución.

Compara la cantidad de trabajo ya completada en un momento dado con la estimación realizada antes del comienzo del proyecto. De este modo, se tiene una medida de cuánto trabajo se ha realizado, cuanto queda para finalizar el proyecto y extrapolando a partir del esfuerzo invertido en el proyecto, el jefe de proyecto puede estimar los recursos que se emplearán para finalizar el proyecto. Con esta metodología se puede estimar en cuanto tiempo se completaría el proyecto si se mantienen las condiciones con las que se elaboró el cronograma o considerando si se mantienen las condiciones que se presentaron durante el desarrollo del proyecto. También se puede estimar el costo total del proyecto.
 </p>
 
 
 <p>
 		PALABRAS CLAVES</p>
        
<p>VARIABLES DE GESTION DE VALOR GANADO</p>
 <p> Valor planeado (PV)</p>
 <p> Valor Ganado (EV)</p>
 <p> Costo Real (AC)   </p>
 <p>VARIACIONES QUE PUEDE PASAR EN UN PROYECTO</p>
 <p> Variación de Costo (CV)   </p>    
 			<p>CV = EV - AC</p>
 <p> Variación del cronograma  (SV)   </p>
    <p>SV = EV-PV   </p>
 <p>CONDICIONES
   PORCENTAJE  </p>
 <p>Porcentaje variación del cronograma </p>
            <p>  SV%= SV/PV   </p>
 <p>Porcentaje variación de Costo   </p>
            <p> CV% =CV/EV </p>
 <p>INDICES   </p>
 <p>Indice de desempeño del presupuesto (CPI)</p>    			  			<p>CPI = EV/AC</p>
 <p> Indice de desempeño del cronograma (SPI)</p>     		  			<p>SPI = EV/PV </p>
 
 
 
 
 <p>
 		 			PALABRAS CLAVES COMPLEMENTARIAS
</p>
 <p>BAC: EL DINERO ESTIMADO PARA EL PROYECTO   </p>
 
 <p>Estimado a la conclusion (EAC)</p>   
 <p>   EAC = BAC/CPI</p>
 <p>Estimado hasta la conclusion (ETC)   </p>
 <p>  ETC = EAC – AC   </p>
 <p>Variaciòn al termino (VAC)  </p> 
 <p>  VAC = BAC-EAC   </p>
 <p>TIEMPO estimado a culminar (EACT)</p>  
 <p> EACT = (BAC/SPI)/(BAC/MESES)</p>
 <p> Indice del desempeño al termino(TCPI) </p> 
   <p>TCPI = BAC-EV/ BAC - AC </p>
   
   <p>EJERCICIO</p>
   
   <p>Una empresa tiene una estimación de  S/. 10,000 al cabo de  10 meses; Al termino del mes 5  se observa que tiene un avance de  30% con un costo de 
S/.4,000.
</p>
   
    <p>RESOLUCION: </p>
<p>VALOR PLANEADO (PV)</p>
	<p>	PV=5000</p>
<p>VALOR GANADO (EV)</p>
	<p>	 (10,000*0.3) =  3,000</p>
<p>COSTO REAL (AC)</p>
	<p>	4,000</p>
<p>VARIACION DEL COSTO (CV)</p>
	<p>	3,000 - 4,000 = -1000</p>
<p>PORCENTAJE DE VARIACION DEL COSTO (%CV)</p>
	<p>	1000/3000= 0.333</p>
<p>VARIACION DEL TIEMPO (SV)</p>
	<p>	3000 – 5000 = -2,000</p>

<p> PORCENTAJE DE VARIACION DEL CRONOGRAMA (%SV)</p>
	<p>	=2,000/5,000= 0.4</p>
<p>INDICE DE DESEMPEÑO DEL COSTO (CPI)</p>
	<p>3000/4000= 0.75</p>
<p>INDICE DE DESEMPEÑO DEL TIEMPO (SPI)</p>
	<p>3000/5000= 0.6</p>
<p>ESTIMADO A LA CONCLUSION  (EAC)</p>
	<p>10000/0.75= 13333.33333</p>
<p>ESTIMADO HASTA LA CONCLUSION  (ETC)</p>
<p>	13333.33333 – 4000 = 9333.33333</p>
<p>VARIACION AL TERMINO  (VAC)</p>
	<p>10000 – 13333.33333 = -3333.33333)  </p>
<p>INDICE DE DESEMPEÑO AL TERMINO  (TCPI)</p>
	<p>(10000-3000)/(10000-4000)= 1.1667
 </p>
   
   
   
   
 
 
 
 
 

 
 
 
 
  
  
 
 
 
      <section>
      <h2>&nbsp;</h2>
      <div align="right">
        <center>
      </center>
    </div>
    </section>
      
    </section>
  <!-- end .content --></article>
  <footer>
    <address>
    <br> <center><div id="anuncio1"><a href="https://es-la.facebook.com/darwin.alaniainocencio" target="new"><img src="envio1/envio1/f.jpg" width="80" height="80" alt=""/></a>
    <a href="https://pe.linkedin.com/pub/darvin-ricardo-alania-inocencio/b9/396/679" target="new"><img src="envio1/envio1/linkedin.jpg" width="80" height="80" alt=""/></a>
      <a href="https://www.youtube.com/channel/UCflwtFGm0qxE9-x3suzK90w/videos" target="new"><img src="envio1/envio1/y.jpg" width="80" height="80" alt=""/> </a>
      <a href="https://mail.google.com/mail/u/0/#inbox" target="new"><img src="envio1/envio1/g.jpg" width="80" height="80" alt=""/></a></div> </center>
    </address>
  </footer>
<!-- end .container --></div>
</body>
</html>
